# Generated by Django 2.2.7 on 2019-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Descripción de ejemplo'),
            preserve_default=False,
        ),
    ]
