# Generated by Django 2.2.7 on 2019-11-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191123_0638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('item', 'order')},
        ),
    ]
